export const countyOptions = [
    { name: "連江縣", geometryIndex: 0 }, 
    { name: "宜蘭縣", geometryIndex: 1 },
    { name: "彰化縣", geometryIndex: 2 },
    { name: "南投縣", geometryIndex: 3 },
    { name: "雲林縣", geometryIndex: 4 }, 
    { name: "屏東縣", geometryIndex: 5 },
    { name: "基隆市", geometryIndex: 6 },
    { name: "臺北市", geometryIndex: 7 },
    { name: "新北市", geometryIndex: 8 }, 
    { name: "台中市", geometryIndex: 9 },
    { name: "臺南市", geometryIndex: 10 },
    { name: "桃園市", geometryIndex: 11 },
    { name: "苗栗縣", geometryIndex: 12 }, 
    { name: "嘉義市", geometryIndex: 13 },
    { name: "嘉義縣", geometryIndex: 14 },
    { name: "金門縣", geometryIndex: 15 },
    { name: "高雄市", geometryIndex: 16 },
    { name: "臺東縣", geometryIndex: 17 },
    { name: "花蓮縣", geometryIndex: 18 },
    { name: "澎湖縣", geometryIndex: 19 }, 
    { name: "新竹市", geometryIndex: 20 },
    { name: "新竹縣", geometryIndex: 21 },
  ];